const data = [
  {
    Tipo: 'Check In',
    Room: '4 X 4 ROOM 202',
    Nombre: 'Nombre1',
    Categoría: 'Hotel',
    Producto: 'Accommodation',
    Monto: 100,
    Moneda: 'Soles',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Check Out',
    Room: 'DORM 102',
    Nombre: 'Nombre2',
    Categoría: 'Hotel',
    Producto: 'Accommodation',
    Monto: 150,
    Moneda: 'USD',
    MetodoPago: 'IZIPAY',
  },
  {
    Tipo: 'Deuda Cloud Beds',
    Room: 'DORM 301',
    Nombre: 'Nombre3',
    Categoría: 'Hotel',
    Producto: 'Accommodation',
    Monto: 80,
    Moneda: 'Soles',
    MetodoPago: 'Transferencia BCP',
  },
  {
    Tipo: 'Cambio USD',
    Room: 'ROOM 201',
    Nombre: 'Nombre4',
    Categoría: 'Hotel',
    Producto: 'Accommodation',
    Monto: 120,
    Moneda: 'USD',
    MetodoPago: 'PAYPAL',
  },
  {
    Tipo: 'Pagos Varios',
    Room: 'ROOM 303',
    Nombre: 'Nombre5',
    Categoría: 'Hotel',
    Producto: 'Accommodation',
    Monto: 200,
    Moneda: 'Soles',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Restaurante',
    Room: 'GUEST',
    Nombre: 'Nombre6',
    Categoría: 'Palate',
    Producto: 'Comida',
    Monto: 50,
    Moneda: 'Soles',
    MetodoPago: 'IZIPAY',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  {
    Tipo: 'Bar',
    Room: 'ROOM 401',
    Nombre: 'Nombre7',
    Categoría: 'Bar',
    Producto: 'Bebidas',
    Monto: 30,
    Moneda: 'USD',
    MetodoPago: 'Efectivo',
  },
  // ... más registros según sea necesario
];

export default data;