import '../globals.css'
import { Inter } from 'next/font/google'
import ReceptionistSidebar from '@/components/ui/receptionistSidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
  <div className='w-screen h-screen flex flex-row'>
    <div className='w-2/12 h-screen mr-3'>
      <ReceptionistSidebar/>
    </div>
    <div className='bg-white w-10/12 h-screen p-6'>
      {children}
    </div>
    
  </div>
  )
}
